# Generated by Django 3.1.3 on 2020-12-08 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visit_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enq_source', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enquiry_number', models.CharField(blank=True, default='eb0dc7df', max_length=100, unique=True)),
                ('Contact_number', models.CharField(max_length=12, unique=True)),
                ('Email', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Company_name', models.CharField(max_length=500)),
                ('Enquiry_details', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('expected_purchase_Date', models.DateField(blank=True, null=True, verbose_name='Expected Purchase Date')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Visit Date')),
                ('visited_status', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1)),
                ('Booking_Date', models.DateField(blank=True, null=True, verbose_name='Booking Date')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('Visit_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm.client_visit')),
                ('enquiry_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm.enquiry_source')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm.profession')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
    ]
