# Generated by Django 3.1.3 on 2021-03-28 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enquiry_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enquiry_number', models.CharField(blank=True, default='RAWIUOGTYL', max_length=100, unique=True)),
                ('Contact_number', models.CharField(max_length=13, unique=True)),
                ('Email', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Company_name', models.CharField(max_length=500)),
                ('Enquiry_details', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Delivery_date', models.DateField()),
                ('Expected_purchase_Date', models.DateField(blank=True, null=True, verbose_name='Expected Purchase Date')),
                ('Visited_status', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1)),
                ('Booking_Date', models.DateField(blank=True, null=True, verbose_name='Booking Date')),
                ('Follow_up', models.DateField(blank=True, null=True, verbose_name='Follow Up Date')),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enq_source', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Update By')),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Visit_status', models.CharField(max_length=100, verbose_name='enquiry status')),
                ('enquiry_status_time', models.DateTimeField(auto_now_add=True)),
                ('Enquiry_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm.enquiry', verbose_name='Enquiry Number ')),
            ],
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Enquiry_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm.enquiry_source'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Enquiry_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm.client_visit'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm.profession'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
    ]
