# Generated by Django 3.1.3 on 2020-12-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry_update',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_status_time',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='CGHLGOZQVN', max_length=100, unique=True),
        ),
    ]
