# Generated by Django 3.1.3 on 2020-12-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='DNGNNKSTLI', max_length=100, unique=True),
        ),
    ]
