# Generated by Django 3.1.3 on 2020-12-08 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0002_auto_20201209_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='visit_status_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='4660976f', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='last_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm.visit_status_time'),
        ),
    ]
