# Generated by Django 3.1.3 on 2020-12-17 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0002_auto_20201213_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='Follow_up',
            field=models.DateField(blank=True, null=True, verbose_name='Follow Up Date'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Contact_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='UTUPJTCPYA', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_status_time',
            field=models.CharField(default='sanju here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='visit_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Visit Date'),
        ),
    ]
