# Generated by Django 3.1.3 on 2020-12-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0003_auto_20201207_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='f3825cdd', max_length=100, unique=True),
        ),
    ]
