# Generated by Django 3.1.3 on 2020-12-21 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0003_auto_20201218_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 21, 17, 31, 38, 5551, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='KLKTLEYZON', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_status_time',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
