# Generated by Django 3.1.3 on 2021-03-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0003_auto_20210330_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Visit_status',
            new_name='Enquiry_status',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='enquiry_status_time',
            new_name='Enquiry_status_time',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='NQWJZAHKAL', max_length=100, unique=True),
        ),
    ]
