# Generated by Django 3.1.3 on 2021-04-05 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0004_auto_20210330_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machinename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Machine_Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Machine Name')),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='TEFJBSJIGC', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm.client_visit'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Machine_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm.machinename'),
        ),
    ]
