# Generated by Django 3.1.3 on 2020-12-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0004_auto_20201221_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='NKSUCMXWAN', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
