# Generated by Django 3.1.3 on 2021-05-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0006_auto_20210502_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='KOHWCGYWNA', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Visited_status',
            field=models.IntegerField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes'),
        ),
    ]
