# Generated by Django 3.1.3 on 2020-12-23 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crm', '0006_auto_20201223_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='UMVLSLIGPH', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='Visit_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Crm.client_visit', verbose_name='enquiry status'),
        ),
        migrations.AlterField(
            model_name='history',
            name='enquiry_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Crm.enquiry', verbose_name='Enquiry Number '),
        ),
        migrations.AlterField(
            model_name='history',
            name='update_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Update By'),
        ),
    ]
