# Generated by Django 3.1.3 on 2021-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0007_auto_20210502_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='JMLSGGXEPB', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Visited_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20),
        ),
    ]
