# Generated by Django 3.1.3 on 2020-12-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0008_auto_20201207_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='9742a8fd', max_length=100, unique=True),
        ),
    ]
