# Generated by Django 3.1.3 on 2020-12-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0008_auto_20201223_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='enquiry_status_time',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='GAZQGCYEFG', max_length=100, unique=True),
        ),
    ]
