# Generated by Django 3.1.3 on 2020-12-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0009_auto_20201224_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='DXXMNRTNAB', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='Visit_status',
            field=models.CharField(max_length=100, verbose_name='enquiry status'),
        ),
        migrations.AlterField(
            model_name='history',
            name='enquiry_number',
            field=models.CharField(max_length=100, verbose_name='Enquiry Number '),
        ),
        migrations.AlterField(
            model_name='history',
            name='update_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Update By'),
        ),
    ]
