# Generated by Django 3.1.3 on 2020-12-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0011_auto_20201224_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='WJKNKEBKDF', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
