# Generated by Django 3.1.3 on 2020-12-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0012_auto_20201225_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='BLOYRZZHGS', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='enquiry_status_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
