# Generated by Django 3.1.3 on 2020-12-28 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0015_auto_20201226_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Contact_number',
        ),
        migrations.AddField(
            model_name='history',
            name='Enquiry_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm.enquiry', verbose_name='Enquiry Number '),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='WURPTNJGZM', max_length=100, unique=True),
        ),
    ]
