# Generated by Django 3.1.3 on 2021-01-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0016_auto_20201228_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='NMRRBVSCVQ', max_length=100, unique=True),
        ),
    ]
