# Generated by Django 3.1.3 on 2021-03-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm', '0017_auto_20210122_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Contact_number',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_number',
            field=models.CharField(blank=True, default='JFBBWTAIMU', max_length=100, unique=True),
        ),
    ]
